name: pcraig
favicon: null
layout_spectrum: 0.08493488607928157
typography_spectrum: 0.5373539521824569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5072609968483448
  lightness: 0.8279261554125696
  saturation: 0.3816793893929571
  rhythmicContrast: 0.7034566113725305
purpose: []
